--- 
:rocket_secure: "yes"
:dps: "yes"
:paypal: "no"
:securepaytech: "no"
:currency_preview: "yes"
:customers_report: "yes"
:products_report: "yes"
:orders_report: "yes"
:weight_cost_options: "yes"
:weight_based_shipping: "yes"
:featured_products: "yes"
:cross_selling: "yes"
:separate_delivery_address: "yes"
:combination_products: "no"
:custom_product_fields: "no"
:gift_certificates: "no"
:product_ratings: "no"
:product_reviews: "no"
:downloadable_products: "no"
